# Schema for the configuration files of the Same Page Preview module.
same_page_preview.settings:
  type: config_object
  label: 'Same Page Preview settings'
  mapping:
    example:
      type: string
      label: 'Example'
